name: basedonissue
on: [issue, workflow_dispatch]
jobs:
  displayissue:
    runs-on: ubuntu-latest
    steps:
      step1:
        - name: echo the ouput
          run: echo "${{toJSON(github.event)}}"
